services:
  # ----------------------------------------- DATABASES ----------------------------------------- #

  postgres:
    image: postgres:latest
    command: postgres -c log_statement=all
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # -------------------------------------- STORAGE BACKENDS ------------------------------------- #

  rustfs:
    image: rustfs/rustfs:latest
    command: /data
    environment:
      RUSTFS_ADDRESS: ":9000"
      RUSTFS_CONSOLE_ADDRESS: ":9001"
      RUSTFS_ACCESS_KEY: rustfsadmin
      RUSTFS_SECRET_KEY: rustfsadmin
      RUSTFS_CONSOLE_ENABLE: "true"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - rustfs_data:/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    command: azurite-blob --blobHost 0.0.0.0 --blobPort 10000
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data

  # fake-gcs-server

volumes:
  postgres_data:
  mysql_data:
  rustfs_data:
  azurite_data:
