import importlib.metadata
import warnings

try:
    __version__ = importlib.metadata.version("ducklake-sdk")
except importlib.metadata.PackageNotFoundError as e:  # pragma: no cover
    warnings.warn(f"Could not determine version of ducklake-sdk\n{e!s}", stacklevel=2)
    __version__ = "unknown"

from .connect import connect, create
from .ducklake import Ducklake
from .table import Table
from .transaction import Transaction
from .typedefs import (
    Blob,
    Boolean,
    Column,
    ColumnStats,
    DataFileStatistics,
    DataType,
    Date,
    Decimal,
    DeleteFile,
    Float32,
    Float64,
    Int8,
    Int16,
    Int32,
    Int64,
    Int128,
    Interval,
    Json,
    List,
    MaintenanceResult,
    Map,
    PartitionColumn,
    Partitioning,
    ScanDataFile,
    ScanResult,
    Schema,
    SnapshotMetadata,
    Struct,
    TableMetadata,
    TableName,
    Time,
    Timestamp,
    TimestampTz,
    TimeTz,
    UInt8,
    UInt16,
    UInt32,
    UInt64,
    UInt128,
    Uuid,
    Varchar,
    WriteDataFile,
)

__all__ = [
    "Blob",
    "Boolean",
    "Column",
    "ColumnStats",
    "connect",
    "create",
    "DataFileStatistics",
    "DataType",
    "Date",
    "Decimal",
    "DeleteFile",
    "Ducklake",
    "Float32",
    "Float64",
    "Int128",
    "Int16",
    "Int32",
    "Int64",
    "Int8",
    "Interval",
    "Json",
    "List",
    "Map",
    "MaintenanceResult",
    "PartitionColumn",
    "Partitioning",
    "ScanDataFile",
    "ScanResult",
    "Schema",
    "SnapshotMetadata",
    "Struct",
    "Table",
    "TableMetadata",
    "TableName",
    "Transaction",
    "Time",
    "Timestamp",
    "TimestampTz",
    "TimeTz",
    "UInt128",
    "UInt16",
    "UInt32",
    "UInt64",
    "UInt8",
    "Uuid",
    "Varchar",
    "WriteDataFile",
]
