import datetime as dt

from .typedefs import (
    ArrowSchemaExportable,
    ArrowStreamExportable,
    Column,
    DataType,
    ScanResult,
    SnapshotMetadata,
    TableMetadata,
    Value,
    WriteDataFile,
)

# ------------------------------------------- DUCKLAKE ------------------------------------------ #

def create(url: str, data_path: str, storage_options: list[tuple[str, str]]) -> PyDucklake: ...
def connect(
    url: str,
    snapshot_id: int | None,
    snapshot_timestamp: dt.datetime | None,
    migrate: bool,
    storage_options: list[tuple[str, str]],
) -> PyDucklake: ...

class PyDucklake:
    def at_snapshot_id(self, snapshot_id: int) -> PyDucklake: ...
    def at_snapshot_timestamp(self, timestamp: dt.datetime) -> PyDucklake: ...
    def get_latest_snapshot(self) -> SnapshotMetadata: ...
    def list_snapshots(self) -> list[SnapshotMetadata]: ...
    def transaction(
        self, author: str | None, message: str | None, extra_info: str | None
    ) -> PyTransaction: ...
    def create_schema(self, name: str, data_path: str | None) -> None: ...
    def delete_schema(self, name: str) -> None: ...
    def create_table(
        self,
        name: str | tuple[str, str],
        columns: list[Column],
        partition: list[tuple[str, str | None, int | None]] | None,
        data_path: str | None,
        tags: list[tuple[str, str]] | None,
    ) -> PyTable: ...
    def table(self, name: str | tuple[str, str]) -> PyTable: ...
    def list_tables(self, schema: str | None) -> list[PyTable]: ...
    def list_schemas(self) -> list[str]: ...
    def set_metadata(self, key: str, value: str | None, schema: str | None) -> None: ...
    def disconnect(self) -> None: ...

# -------------------------------------------- TABLE -------------------------------------------- #

class PyTable:
    @property
    def name(self) -> tuple[str, str]: ...
    @property
    def columns(self) -> list[Column]: ...
    @property
    def partitioning(self) -> list[tuple[str, str | None, int | None]] | None: ...
    @property
    def tags(self) -> list[tuple[str, str]]: ...
    @property
    def metadata(self) -> TableMetadata: ...
    @property
    def data_path(self) -> str: ...
    def rename(self, new_name: str) -> None: ...
    def update_partitioning(
        self, partitioning: list[tuple[str, str | None, int | None]] | None
    ) -> None: ...
    def add_column(self, column: Column) -> None: ...
    def rename_column(self, column: str, new_name: str) -> None: ...
    def remove_column(self, column: str) -> None: ...
    def update_column_dtype(self, column: str, new_dtype: DataType) -> None: ...
    def update_column_default(
        self, column: str, default_value: Value | tuple[str, str] | None
    ) -> None: ...
    def update_column_nullability(self, column: str, nullable: bool) -> None: ...
    def update_schema(self, schema: list[Column]) -> None: ...
    def delete(self) -> None: ...
    def add_tag(self, key: str, value: str) -> None: ...
    def remove_tag(self, key: str) -> None: ...
    def add_column_tag(self, column: str | list[str], key: str, value: str) -> None: ...
    def remove_column_tag(self, column: str | list[str], key: str) -> None: ...
    def get_write_info(self) -> tuple[TableMetadata, PyDataFilePathGenerator]: ...
    def write_data_files(self, new_data_files: list[WriteDataFile]) -> None: ...
    def write_inline_data(self, data: ArrowStreamExportable) -> None: ...
    def scan(self) -> ScanResult: ...
    def set_metadata(self, key: str, value: str | None) -> None: ...

# ----------------------------------------- TRANSACTION ----------------------------------------- #

class PyTransaction:
    def create_schema(self, name: str, data_path: str | None) -> None: ...
    def delete_schema(self, name: str) -> None: ...
    def table(self, name: str | tuple[str, str]) -> PyTransactionTable: ...
    def create_table(
        self,
        name: str | tuple[str, str],
        schema: list[Column],
        partition: list[tuple[str, str | None, int | None]] | None,
        data_path: str | None,
        tags: list[tuple[str, str]] | None,
    ) -> PyTransactionTable: ...
    def commit(self) -> None: ...

class PyTransactionTable:
    @property
    def columns(self) -> list[Column]: ...
    @property
    def partitioning(self) -> list[tuple[str, str | None, int | None]] | None: ...
    def rename(self, new_name: str) -> None: ...
    def update_partitioning(
        self, partitioning: list[tuple[str, str | None, int | None]] | None
    ) -> None: ...
    def add_column(self, column: Column) -> None: ...
    def rename_column(self, column: str | list[str], new_name: str) -> None: ...
    def remove_column(self, column: str | list[str]) -> None: ...
    def update_column_dtype(self, column: str, new_dtype: DataType) -> None: ...
    def update_column_default(
        self, column: str, default_value: Value | tuple[str, str] | None
    ) -> None: ...
    def update_column_nullability(self, column: str, nullable: bool) -> None: ...
    def update_schema(self, schema: list[Column]) -> None: ...
    def delete(self) -> None: ...
    def add_tag(self, key: str, value: str) -> None: ...
    def remove_tag(self, key: str) -> None: ...
    def add_column_tag(self, column: str | list[str], key: str, value: str) -> None: ...
    def remove_column_tag(self, column: str | list[str], key: str) -> None: ...
    def get_write_info(self) -> tuple[TableMetadata, PyDataFilePathGenerator]: ...
    def write_data_files(self, data_files: list[WriteDataFile]) -> None: ...
    def write_inline_data(self, data: ArrowStreamExportable) -> None: ...

# ------------------------------------------ EXCEPTIONS ----------------------------------------- #

class AlreadyExistsError(Exception): ...
class AlreadyInitializedError(Exception): ...
class OutdatedVersionError(Exception): ...
class NotFoundError(Exception): ...
class NotInitializedError(Exception): ...
class InvalidCastError(Exception): ...
class InvalidNullValueError(Exception): ...
class InvalidNullabilityChangeError(Exception): ...
class TransactionConflictError(Exception): ...
class ImmutableDucklakeError(Exception): ...

# -------------------------------------------- UTILS -------------------------------------------- #

def arrow_schema_field_ids(schema: ArrowSchemaExportable) -> dict[int, str]: ...
def schema_to_arrow(columns: list[Column]) -> ArrowSchemaExportable: ...

class PyDataFilePathGenerator:
    @property
    def base_path(self) -> str: ...
    def generate_relative(self, partition_values: list[tuple[str, Value]]) -> str: ...
    def generate_absolute(self, partition_values: list[tuple[str, Value]]) -> str: ...
